### ISSUE TITLE
Unable to change number of threads

### ISSUE THREAD

**Issue by tmpolaczyk** [stampery-labs/witnet-vanity#1]
It looks like the `-t` flag is ignored:

```
witnet-vanity -t 1 aaaa
```

This spawns more than 1 thread. Probably it's because the flag is not being read correctly, here instead of `num-cpus` it should say `threads`:

https://github.com/stampery-labs/witnet-vanity/blob/17f72e4fdff4cac7b15510b28164d38c02a81000/src/main.rs#L209

Bonus points for replacing `clap` with `structopt`, which eliminates this kind of problems.

**Comment by mariocao** [comment]
I just amended it! It should be fixed right now. :smile:
